### ISSUE TITLE
variableMeasured not being populated for icephys

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1016]
e.g. https://dandiarchive.org/dandiset/000109 contains neurodata type VoltageClampSeries. This is supposed to add VoltageClampSeries to the variableMeasured attribute of the assetsSummary ([here](https://github.com/dandi/dandi-cli/blob/d061e3a02f51e0e2067a7ca0cf450b269f2f008e/dandi/tests/test_metadata.py#L456-L460)), however this field is not populated. This problem shows up in many of the icephys datasets, and does not appear to be a problem for ecephys and ophys.

**Comment by satra** [comment]
the metadata extraction wasn't available in the earliest days of the archive. that's an old dandiset. was it run through the current cli ? can you re-upload the asset with the current cli with `--existing replace` (i think), and see if it changes?

**Comment by bendichter** [comment]
"replace" is not an option. The options are: error|skip|force|overwrite|refresh. Do you mean "force"?

**Comment by satra** [comment]
i think `overwrite`

**Comment by satra** [comment]
if it works the asset metadata should contain the voltageclampseries.

**Comment by satra** [comment]
you can also test by using dandi ls locally on the nwb file

**Comment by bendichter** [comment]
dandi ls seems to work:
```
(base) MacBook-Pro-3:sub-mouse-AAYYT bendichter$ dandi ls sub-mouse-AAYYT_ses-20180420-sample-2_slice-20180420-slice-2_cell-20180420-sample-2_icephys.nwb
- age: P148D
  cell_id: 20180420_sample_2
  date_of_birth: 2017-11-23 00:00:00-05:00
  experiment_description: Current clamp square
  experimenter:
  - Matteo Bernabucci
  genotype: wt/wt
  identifier: dcf5e2ab-2b96-492f-beb8-1f4dc6fabd52
  institution: Baylor College of Medicine
  keywords: null
  lab: Tolias
  nd_types:
  - CreSubject
  - CurrentClampSeries (79)
  - CurrentClampStimulusSeries (79)
  - DandiIcephysMetadata
  - Device (161)
  - IZeroClampSeries
  - IntracellularElectrode (160)
  - SweepTable
  number_of_electrodes: 0
  number_of_units: 0
  nwb_version: 2.2.5
  path: sub-mouse-AAYYT_ses-20180420-sample-2_slice-20180420-slice-2_cell-20180420-sample-2_icephys.nwb
  related_publications: null
  session_description: Current clamp square
  session_id: 20180420_sample_2
  session_start_time: 2018-04-20 00:00:00-04:00
  sex: F
  size: 9337840
  slice_id: 20180420_slice_2
  species: null
  subject_id: mouse_AAYYT
```

Here is the description of the options:

> What to do if a file found existing on the
server.
'skip' would skip the file,
'force' - force reupload, 'overwrite' - force upload
if either size or modification time differs;
'refresh' - upload only if local
modification time is ahead of the remote.

overwrite does not do anything because there is no difference in size or modification time. Should I try replace?
